
services:
  - type: web
    name: aqua-web-services
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn AquaKeeper.web.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
